# Generated by Django 4.2.2 on 2023-06-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_perfil_fondoperfil_alter_perfil_imgperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='FondoPerfil',
            field=models.ImageField(blank=True, default='Media/IMGDefault/FondoPerfil.png', max_length=200, null=True, upload_to='IMGFondo', verbose_name='Fondo de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='IMGPerfil',
            field=models.ImageField(blank=True, default='Media/IMGDefault/imagenPerfil.png', max_length=255, null=True, upload_to='IMGPerfil', verbose_name='Imagen de perfil'),
        ),
    ]
