# Generated by Django 4.2.2 on 2023-06-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_perfil_fondoperfil_alter_perfil_imgperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='FondoPerfil',
            field=models.ImageField(blank=True, default='imagenes/FondoPerfil.png', max_length=200, null=True, upload_to='IMGFondo/', verbose_name='Fondo de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='IMGPerfil',
            field=models.ImageField(blank=True, default='Imagenes/imagenPerfil.png', max_length=255, null=True, upload_to='IMGPerfil/', verbose_name='Imagen de perfil'),
        ),
    ]
