# Generated by Django 4.2.2 on 2023-06-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_perfil_fondoperfil_alter_perfil_imgperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='FondoPerfil',
            field=models.ImageField(default='C:\\Users\\PC\\Documents\\Universidad\\Ciclo I 2023 UES\\Analisis numericos\\ANS-ProyectoFinal\\static/IMG/FondoPerfil.png', max_length=200, null=True, upload_to='Media/IMGFondo/', verbose_name='Fondo de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='IMGPerfil',
            field=models.ImageField(default='C:\\Users\\PC\\Documents\\Universidad\\Ciclo I 2023 UES\\Analisis numericos\\ANS-ProyectoFinal\\static/IMG/imagenPerfil.png', max_length=255, null=True, upload_to='Media/IMGPerfil', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
