# Generated by Django 4.2.2 on 2023-06-23 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0010_alter_perfil_imgperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='FondoPerfil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='IMGPerfil',
        ),
        migrations.CreateModel(
            name='Profile_IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMGPerfil', models.ImageField(blank=True, default='C:\\Users\\PC\\Documents\\Universidad\\Ciclo I 2023 UES\\Analisis numericos\\ANS-ProyectoFinal\\static/IMG/imagenPerfil.png', max_length=255, null=True, upload_to='Media/IMGPerfil', verbose_name='Imagen de perfil')),
                ('FondoPerfil', models.ImageField(blank=True, default='C:\\Users\\PC\\Documents\\Universidad\\Ciclo I 2023 UES\\Analisis numericos\\ANS-ProyectoFinal\\static/IMG/FondoPerfil.png', max_length=200, null=True, upload_to='Media/IMGFondo/', verbose_name='Fondo de perfil')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
