# Generated by Django 4.2.2 on 2023-06-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_perfil_fondoperfil_remove_perfil_imgperfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='FondoPerfil',
            field=models.ImageField(default='static/IMG/FondoPerfil.png', max_length=200, upload_to='Media/IMGFondo/', verbose_name='Fondo de perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='IMGPerfil',
            field=models.ImageField(default='static/IMG/imagenPerfil.png', max_length=255, upload_to='Media/IMGPerfil', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.DeleteModel(
            name='Profile_IMG',
        ),
    ]
